name: deploy-infra-app-homolog

on:
  workflow_call:

    inputs:
      my_env:
        type: string
        required: true

env:
  OUTRA_ENV: BLEH

jobs:
  deploy-homolog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      
      - name: Run
        run:
          echo RUN
          env