name: deploy-infra-app-homolog

on:
  workflow_call:

    inputs:
      my_env:
        type: string
        required: true

env:
  OUTRA_ENV: BLEH

jobs:
  deploy-homolog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      
      - name: Run
        env:
          ENV_SECRET_LOCAL: ${{ secrets.ENV_SECRET }}
          MINHA_SECRET_PAI_LOCAL: ${{ secrets.MINHA_SECRET_PAI }}
          MINHA_SECRET_LOCAL: ${{ secrets.MINHA_SECRET }}
        run: |
          echo RUN
          env
          echo ENV_SECRET: $ENV_SECRET  
          echo ENV_SECRET_LOCAL: $ENV_SECRET_LOCAL
          echo MINHA_SECRET: $MINHA_SECRET
          echo MINHA_SECRET_PAI_LOCAL: $MINHA_SECRET_PAI_LOCAL
          echo MINHA_SECRET_LOCAL: $MINHA_SECRET_LOCAL
